-- 脱敏患者姓名
UPDATE [dbo].[PAT_VISIT] 
	SET NAME = REPLACE( NAME, SUBSTRING ( NAME, 2, 3 ), '**' ) 
WHERE
	NAME != '' 
	
-- 脱敏身份证
UPDATE [dbo].[PAT_SD_ITEM_RESULT] 
	SET SD_ITEM_VALUE = REPLACE( SD_ITEM_VALUE, SUBSTRING ( SD_ITEM_VALUE, 4, LEN( SD_ITEM_VALUE ) -1 ), '**************' ) 
WHERE
	SD_ITEM_CODE = 'YXA_O_001' 
	AND SD_ITEM_VALUE != '' 
	
-- 脱敏地址
UPDATE [dbo].[PAT_SD_ITEM_RESULT] 
	SET SD_ITEM_VALUE = REPLACE( SD_ITEM_VALUE, SUBSTRING ( SD_ITEM_VALUE, 4, LEN( SD_ITEM_VALUE ) ), '**********' ) 
WHERE
	SD_ITEM_CODE = 'YXA_O_003' 
	AND SD_ITEM_VALUE != '' 

-- 脱敏手机号
UPDATE [dbo].[PAT_SD_ITEM_RESULT] 
	SET SD_ITEM_VALUE = REPLACE( SD_ITEM_VALUE, SUBSTRING ( SD_ITEM_VALUE, 4, 4 ), '****' ) 
WHERE
	SD_ITEM_CODE = 'YXA_O_004' 
	AND SD_ITEM_VALUE != '' 
	
-- 脱敏主刀医师
UPDATE [dbo].[PAT_SD_ITEM_RESULT] 
	SET SD_ITEM_VALUE = REPLACE( SD_ITEM_VALUE, SUBSTRING ( SD_ITEM_VALUE, 2, LEN( SD_ITEM_VALUE ) ), '**' ) 
WHERE
	SD_ITEM_CODE = 'YXA_O_005' 
	AND SD_ITEM_VALUE != ''