-- 	术前评估“可切除”的（9036）胰腺导管腺癌+至少一次随访（7066）-围手术期死亡（30天内死亡（88）+院内死亡(76)）(156)-其它原因死亡（出血+心脑血管疾病+意外）（7038）
-- 查询并创建入组表（6961）

-- 查询围手术期(30天内)死亡的患者
SELECT
	die.PATIENT_NO INTO #perioperative_period 
FROM
	(-- 院内死亡
	SELECT DISTINCT
		a.PATIENT_NO 
	FROM
		[dbo].[PAT_SD_ITEM_RESULT] AS a 
	WHERE
		a.SD_ITEM_CODE = 'YXA_O_209' 
		AND a.SD_ITEM_VALUE= '1' 
		AND a.PATIENT_NO IN ( SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O' ) 
    
    UNION
    
    -- 死亡日期 减去 手术日期 小于等于30天
	SELECT DISTINCT
		a.PATIENT_NO 
	FROM
		[dbo].[PAT_SD_ITEM_RESULT] AS a
		LEFT JOIN [dbo].[PAT_FOLLOW_UP_RESULT] AS b ON b.SD_ITEM_CODE = 'YXA_O_257' -- 随访死亡日期
		
		AND b.SD_ITEM_VALUE != '' 
	WHERE
		a.SD_ITEM_CODE= 'YXA_O_161' -- 手术日期
		
		AND a.SD_ITEM_CODE!= '' 
		AND b.PATIENT_NO= a.PATIENT_NO 
		AND a.PATIENT_NO IN ( SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O' ) 
		AND DATEDIFF(
			mm,
			CONVERT ( VARCHAR ( 100 ), a.SD_ITEM_VALUE, 120 ),
			CONVERT ( VARCHAR ( 100 ), b.SD_ITEM_VALUE, 120 ) 
		) <= '1' 
	) AS die	


	-- 至少一次随访
	SELECT DISTINCT
		PATIENT_NO 
		INTO #in_group
	FROM
		[dbo].[PAT_FOLLOW_UP] 
	WHERE
		FOLLOW_UP_DATE != '1900-01-01 00:00:00.000' 
		AND PATIENT_NO IN (
		-- 可切除
		SELECT
			ids.PATIENT_NO 
		FROM
			[dbo].[tmp_id] AS ids
			LEFT JOIN [dbo].[PAT_SD_ITEM_RESULT] AS r ON ids.PATIENT_NO= r.PATIENT_NO 
		WHERE
			SD_ITEM_CODE = 'YXA_O_149' 
			AND SD_ITEM_VALUE = '1' 
		) 
		AND PATIENT_NO NOT IN (-- 其它原因死亡（出血+心脑血管疾病+意外）
		SELECT
			r.PATIENT_NO 
		FROM
			[dbo].[PAT_FOLLOW_UP_RESULT] AS r
			LEFT JOIN [dbo].[SD_ITEM_CV_DICT] AS d ON r.SD_ITEM_VALUE= d.CV_VALUE 
			AND d.CV_CODE= 'SWYY' 
		WHERE
			SD_ITEM_CODE = 'YXA_O_258' 
			AND d.CV_VALUE_TEXT!= '' 
			AND d.CV_VALUE IN ( '3', '4', '5' ) 
		) 
		AND PATIENT_NO NOT IN (-- 查询围手术期(30天内)死亡的患者 将查询到的 PATIENT_NO 放在这里
			SELECT PATIENT_NO FROM #perioperative_period
		) 
		


-- 	6961里有复发转移时间的（1899）

SELECT DISTINCT
	a1.PATIENT_NO 
FROM
	[dbo].[PAT_FOLLOW_UP_RESULT] AS a1
-- 	LEFT JOIN [dbo].[PAT_SD_ITEM_RESULT] AS a2 ON a1.PATIENT_NO= a2.PATIENT_NO 
-- 	AND a2.SD_ITEM_CODE= 'YXA_O_161'  -- 手术时间
WHERE
	a1.SD_ITEM_CODE IN ('YXA_O_251','YXA_O_254') -- 有复发转移的
	AND a1.SD_ITEM_VALUE != '' 
	-- 	AND DATEDIFF(mm,CONVERT ( VARCHAR ( 100 ), a2.SD_ITEM_VALUE, 120 ),CONVERT ( VARCHAR ( 100 ), a1.SD_ITEM_VALUE, 120 ) ) <='12'
	-- 	AND DATEDIFF(mm,CONVERT ( VARCHAR ( 100 ), a2.SD_ITEM_VALUE, 120 ),CONVERT ( VARCHAR ( 100 ), a1.SD_ITEM_VALUE, 120 ) ) >='0'
	AND a1.PATIENT_NO IN (
	
		SELECT PATIENT_NO FROM #in_group
	)
	
	
	
-- 	从6961入组中找出有死亡时间的（2106）

SELECT DISTINCT
	a1.PATIENT_NO 
FROM
	[dbo].[PAT_FOLLOW_UP_RESULT] AS a1
-- 	LEFT JOIN [dbo].[PAT_SD_ITEM_RESULT] AS a2 ON a1.PATIENT_NO= a2.PATIENT_NO 
-- 	AND a2.SD_ITEM_CODE= 'YXA_O_161'  -- 手术时间
WHERE
	a1.SD_ITEM_CODE = 'YXA_O_257' -- 有死亡时间的
	AND a1.SD_ITEM_VALUE != '' 
-- 		AND DATEDIFF(mm,CONVERT ( VARCHAR ( 100 ), a2.SD_ITEM_VALUE, 120 ),CONVERT ( VARCHAR ( 100 ), a1.SD_ITEM_VALUE, 120 ) ) <='12'
-- 		AND DATEDIFF(mm,CONVERT ( VARCHAR ( 100 ), a2.SD_ITEM_VALUE, 120 ),CONVERT ( VARCHAR ( 100 ), a1.SD_ITEM_VALUE, 120 ) ) >='0'
	
	AND a1.PATIENT_NO IN (
	
		SELECT PATIENT_NO FROM #in_group
	)

	