-- 	去掉不可切除和术前放化疗
	SELECT
		DISTINCT PATIENT_NO
-- 		*
	FROM
		[dbo].[PAT_SD_ITEM_RESULT] 
	WHERE
		(SD_ITEM_CODE = 'YXA_O_149' AND SD_ITEM_VALUE='1')
		OR (SD_ITEM_CODE = 'YXA_O_117' AND SD_ITEM_VALUE='2')
		AND PATIENT_NO IN (SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O')