SELECT
	PATIENT_NO,
	MAX ( FOLLOW_UP_MONTHS ) AS '随访月份'
FROM
	[dbo].[PAT_FOLLOW_UP] 
WHERE
	FOLLOW_UP_DATE != '1900-01-01 00:00:00.000' 
	AND FOLLOW_UP_MONTHS!=''
	AND FOLLOW_UP_MONTHS <= 12 -- 一年内
	AND PATIENT_NO IN (SELECT
	DISTINCT PATIENT_NO
FROM
	[dbo].[PAT_FOLLOW_UP_RESULT] 
WHERE
	SD_ITEM_VALUE = '2' 
	AND (
	SD_ITEM_CODE = 'YXA_O_250'
	OR SD_ITEM_CODE = 'YXA_O_253')
	AND PATIENT_NO IN ( SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O' )  ) 
GROUP BY
	PATIENT_NO