	SELECT 
	fu_count AS '随访次数',
	COUNT(fu_count) AS '患者数'
	FROM (SELECT
		PATIENT_NO,
		COUNT(PATIENT_NO) AS 'fu_count'
	FROM
		[dbo].[PAT_FOLLOW_UP] 
	WHERE
		FOLLOW_UP_DATE != '1900-01-01 00:00:00.000' 
		AND FOLLOW_UP_MONTHS!=''
		AND PATIENT_NO IN ( SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O' )
	GROUP BY PATIENT_NO
	) AS fu
	GROUP BY fu_count
	ORDER BY fu_count
