
-- 查询每家医院患者数
SELECT
	h.HOSPITAL_NAME AS '医院',
	COUNT(pat.PATIENT_NO) AS '上报数'
FROM
	[dbo].[HOSPITAL_DICT] AS h
	LEFT JOIN [dbo].[PAT_VISIT] AS pat ON h.HOSPITAL_ID=pat.HOSPITAL_ID AND SD_CODE='YXA_O'
	GROUP BY h.HOSPITAL_NAME
	ORDER BY '上报数' DESC