-- [dbo].[PAT_VISIT] AS 					A 	患者基本信息表
-- [dbo].[PAT_SD_ITEM_RESULT] AS 	B 	数据元表
-- [dbo].[SD_ITEM_DICT] AS 				C 	数据项字段
-- [dbo].[SD_ITEM_CV_DICT] AS 		D 	数据元字典

SELECT
	A.PATIENT_NO,
-- 	B.SD_ITEM_CODE,
	C.ITEM_NAME,
	C.ITEM_CV_CODE,
	B.SD_ITEM_VALUE,
	C.ITEM_UNIT as '单位'
FROM
	[dbo].[PAT_VISIT] AS A 
	LEFT JOIN [dbo].[PAT_SD_ITEM_RESULT] AS B ON A.PATIENT_NO= B.PATIENT_NO 
	LEFT JOIN [dbo].[SD_ITEM_DICT] AS C ON B.SD_ITEM_CODE= C.ITEM_CODE
-- 	LEFT JOIN [dbo].[SD_ITEM_CV_DICT] AS D ON C.ITEM_CV_CODE= D.CV_CODE
WHERE
	A.INP_NO = '2392449'
	ORDER BY C.DISPLAY_ORDER
