-- 院内死亡
SELECT 
	PATIENT_NO
FROM
	[dbo].[PAT_SD_ITEM_RESULT] 
WHERE
	SD_ITEM_CODE = 'YXA_O_209'
	AND SD_ITEM_VALUE='1'
	AND PATIENT_NO IN (SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O')