SELECT
	PATIENT_NO,
	FU_TIMES,
	TREAT_NAME AS '治疗方式',
	DRUG_NAME AS '药品名称(通用名)',
	DRUG_NAME_TRADE AS '药品名称(商品名)',
	DRUG_DOSE AS '剂量',
	TREAT_CYCLE AS '疗程/周期',
	TREAT_METHOD AS '化疗方法',
	TREAT_EFFECT AS '是否好转',
	TREAT_COST AS '化疗费用',
	CA199_FRONT AS '治疗前CA199',
	CEA_FRONT AS '治疗前CEA',
	CA125_FRONT AS '治疗前CA125',
	TREAT_EVALUTE_FRONT AS '术前CT评价',
	CA199_AFTER AS '治疗后CA199',
	CEA_AFTER AS '治疗后CEA',
	CA125_AFTER AS '治疗后CA125',
	TREAT_EVALUTE_AFTER AS '术后CT评价' 
FROM
	[dbo].[PAT_FOLLOW_UP_TREAT]