-- 更新手术时间格式
UPDATE [dbo].[PAT_SD_ITEM_RESULT] SET SD_ITEM_VALUE=CAST(SD_ITEM_VALUE AS date) WHERE SD_ITEM_CODE='YXA_O_161' AND SD_ITEM_VALUE!=''
-- 更新死亡时间格式
UPDATE [dbo].[PAT_FOLLOW_UP_RESULT] SET SD_ITEM_VALUE=CAST(SD_ITEM_VALUE AS date) WHERE SD_ITEM_CODE = 'YXA_O_257' AND SD_ITEM_VALUE!=''


-- 查询患者应随访的次数
SELECT
	a.PATIENT_NO,
  	CONVERT (DATE, a.SD_ITEM_VALUE ) AS '手术日期',
	b.SD_ITEM_VALUE AS '死亡日期',
	CONVERT (DATE, ISNULL(b.SD_ITEM_VALUE, GETDATE()) ) AS '截止随访时间',
	DATEDIFF(
		MM,
		CONVERT (DATE, a.SD_ITEM_VALUE ),
		CONVERT (DATE, ISNULL(b.SD_ITEM_VALUE, GETDATE()) )
		)  AS DiffDate
	FROM
		[dbo].[PAT_SD_ITEM_RESULT] AS a
		LEFT JOIN [dbo].[PAT_FOLLOW_UP_RESULT] AS b ON b.SD_ITEM_CODE = 'YXA_O_257' 
		AND b.SD_ITEM_VALUE != '' 
		AND a.PATIENT_NO= b.PATIENT_NO 
	WHERE
		a.SD_ITEM_CODE = 'YXA_O_161' 
		AND a.SD_ITEM_VALUE != '' 