SELECT
DISTINCT a.PATIENT_NO
-- a.PATIENT_NO,
-- a.SD_ITEM_CODE,
-- CONVERT ( VARCHAR ( 100 ), a.SD_ITEM_VALUE, 120 ) AS '手术日期',
-- b.SD_ITEM_CODE,
-- CONVERT ( VARCHAR ( 100 ), b.SD_ITEM_VALUE, 120 ) AS '随访死亡日期',
-- DATEDIFF(
-- 	mm,
-- 	CONVERT ( VARCHAR ( 100 ), a.SD_ITEM_VALUE, 120 ),
-- 	CONVERT ( VARCHAR ( 100 ), b.SD_ITEM_VALUE, 120 ) 
-- ) 
FROM
	[dbo].[PAT_SD_ITEM_RESULT] AS a
	LEFT JOIN [dbo].[PAT_FOLLOW_UP_RESULT] AS b ON b.SD_ITEM_CODE = 'YXA_O_257' -- 随访死亡日期
	
	AND b.SD_ITEM_VALUE != '' 
WHERE
	a.SD_ITEM_CODE= 'YXA_O_161' -- 手术日期
	
	AND a.SD_ITEM_CODE!= '' 
	AND b.PATIENT_NO= a.PATIENT_NO 
	AND a.PATIENT_NO IN (
	SELECT
		PATIENT_NO 
	FROM
		[dbo].[PAT_SD_ITEM_RESULT] 
	WHERE
		SD_ITEM_CODE = 'YXA_O_151' 
		AND ( SD_ITEM_VALUE = '1' OR SD_ITEM_VALUE = '2' OR SD_ITEM_VALUE = '3' OR SD_ITEM_VALUE = '12' ) 
		AND PATIENT_NO IN ( SELECT PATIENT_NO FROM [dbo].[PAT_VISIT] WHERE SD_GROUP = '1' AND SD_CODE = 'YXA_O' ) 
	) 
	AND DATEDIFF(
		mm,
		CONVERT ( VARCHAR ( 100 ), a.SD_ITEM_VALUE, 120 ),
		CONVERT ( VARCHAR ( 100 ), b.SD_ITEM_VALUE, 120 ) 
	) <= '12' 
	AND DATEDIFF(
		mm,
		CONVERT ( VARCHAR ( 100 ), a.SD_ITEM_VALUE, 120 ),
	CONVERT ( VARCHAR ( 100 ), b.SD_ITEM_VALUE, 120 ) 
	) > '0'
	ORDER BY a.PATIENT_NO