-- 计算医院的患者死亡率

SELECT 
	h.HOSPITAL_CODE,
	h.HOSPITAL_CITY,
	COUNT	( DISTINCT fu_r.PATIENT_NO ) AS cout,
	SUM ( CASE WHEN fu_r.SD_ITEM_VALUE= 1 THEN 1 ELSE 0 END ) AS 死亡
-- 	SUM ( CASE WHEN fu_r.SD_ITEM_VALUE= 2 THEN 1 ELSE 0 END ) AS 存活
	-- 	item_r.SD_ITEM_VALUE AS '手术日期'
FROM
	[dbo].[PAT_FOLLOW_UP_RESULT] AS fu_r
	LEFT JOIN [dbo].[PAT_VISIT] AS pat ON fu_r.PATIENT_NO= pat.PATIENT_NO
	LEFT JOIN [dbo].[HOSPITAL_DICT] AS h ON pat.HOSPITAL_ID= h.HOSPITAL_ID
	LEFT JOIN [dbo].[PAT_SD_ITEM_RESULT] AS item_r ON fu_r.PATIENT_NO= item_r.PATIENT_NO 
	AND item_r.SD_ITEM_CODE= 'YXA_O_161'  -- 手术日期
WHERE
	fu_r.SD_ITEM_CODE = 'YXA_O_256' -- 是否死亡
	AND item_r.SD_ITEM_VALUE>= '2017-01-01 00:00:00' 
	AND item_r.SD_ITEM_VALUE<= '2017-12-31 00:00:00' 
GROUP BY h.HOSPITAL_CODE,h.HOSPITAL_CITY
ORDER BY cout DESC